<html>
    <body>
        <table>
            <tr>
                <th>id</th>
                <th>username</th>
                <th>email</th>
                <th>telefone</th>
                <th>telemovel</th>
                <th>permissao</th>
                <th>eliminar</th>
            </tr>
            <tr>
                <td>-1</td>
                <td>userteste</td>
                <td>email@isel.come</td>
                <td>212345678</td>
                <td>915770011</td>
                <td>9000</td>
                <td><button>x</button></td>
            </tr>
        </table>
    </body>
</html>

